import board.Board;
import board.CoordinateTransformation;
import board.Piece;
import parser.PieceReader;
import renderer.AsciiBoardRenderer;
import renderer.PlacementCoordinatesRenderer;
import solver.PlaceAllPiecesBruteForce;

import java.io.File;
import java.io.IOException;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ValatrisSolver {

    public static void main(String[] args) {
        var board = new Board(4, 4);

        try {
            var pieces = new PieceReader().readPieces(new File("palikkatiedosto.txt"));
            var solutionStrategy = new PlaceAllPiecesBruteForce();
            boolean foundSolution = solutionStrategy.solve(board, pieces);
            if (foundSolution) {
                try {
                    new PlacementCoordinatesRenderer().render(board, System.out);
                    System.out.println("");
                    new AsciiBoardRenderer().render(board, System.out);
                    System.out.println("");
                } catch (IOException e) {
                    System.out.println("Failed to render solution: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
