import board.Board;
import board.CoordinateTransformation;
import board.Piece;
import solver.PlaceAllPiecesBruteForce;

import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ValatrisSolver {

    public static void main(String[] args) {
        var board = new Board(4, 4);
        var pieces = List.of(
                new Piece("L",
                        new CoordinateTransformation(0,0),
                        new CoordinateTransformation(1,0),
                        new CoordinateTransformation(0,1)
                ),
                new Piece(
                        "T",
                        new CoordinateTransformation(-1,0),
                        new CoordinateTransformation(0,0),
                        new CoordinateTransformation(1,0),
                        new CoordinateTransformation(0,1)
                ),
                new Piece(
                        "I",
                        new CoordinateTransformation(0,0),
                        new CoordinateTransformation(0,1),
                        new CoordinateTransformation(0,2)
                )
        );

        var solutionStrategy = new PlaceAllPiecesBruteForce();
        var foundSolution = solutionStrategy.solve(board, pieces);

        System.out.println("Found solution? " + foundSolution);

    }
}
