/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ValatrisSolverTest {
    @Test public void testAppHasAGreeting() {
        ValatrisSolver classUnderTest = new ValatrisSolver();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
